# Generated by Django 5.2.7 on 2025-11-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acesso',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
