# Generated by Django 5.2.7 on 2025-11-13 00:37

from django.db import migrations, models


def copiar_justificativas(apps, schema_editor):
    Acesso = apps.get_model('core', 'Acesso')
    for acesso in Acesso.objects.all():
        texto = (getattr(acesso, 'justificativa', '') or '').strip()
        if texto:
            acesso.justificativa_padrao = 'OUTROS'
            acesso.observacao = texto[:200]
        acesso.save(update_fields=['justificativa_padrao', 'observacao'])


def desfazer_copia(apps, schema_editor):
    # Campo removido; nenhuma ação no rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_acesso_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='acesso',
            name='justificativa_padrao',
            field=models.CharField(
                choices=[
                    ('RETIRADA_CAMPO', 'Retirada de insumo para campo'),
                    ('DEVOLUCAO', 'Devolucao de material ao estoque'),
                    ('VERIFICACAO', 'Verificacao de estoque'),
                    ('MANUTENCAO', 'Manutencao no almoxarifado'),
                    ('FISCALIZACAO', 'Fiscalizacao interna'),
                    ('OUTROS', 'Outros'),
                ],
                default='RETIRADA_CAMPO',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name='acesso',
            name='observacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RunPython(copiar_justificativas, desfazer_copia),
        migrations.RemoveField(
            model_name='acesso',
            name='justificativa',
        ),
    ]
