# Generated by Django 5.2.7 on 2025-11-13 01:22

from django.db import migrations, models


def atualizar_status(apps, schema_editor):
    Acesso = apps.get_model('core', 'Acesso')
    Acesso.objects.filter(ativo=False).update(status='FECHADO')
    Acesso.objects.filter(ativo=True).update(status='ABERTO')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_update_justificativa_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='acesso',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acesso',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=20),
        ),
        migrations.RunPython(atualizar_status, migrations.RunPython.noop),
    ]
